name: ml-tf
channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py310h3406613_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.1.0=py310hea6c23e_4
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.2=pyhd8ed1ab_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py310h34a4b09_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cryptography=45.0.7=py310hed992bd_1
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - flatbuffers=23.5.26=h59595ed_1
  - frozenlist=1.7.0=py310h9548a50_0
  - gast=0.6.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - google-auth=2.40.3=pyhd8ed1ab_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=nompi_py310h4aa865e_101
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=35_h59b9bed_openblas
  - libcblas=3.9.0=35_he106b2a_openblas
  - libcudnn=9.10.1.4=h7d33bf5_0
  - libcudnn-dev=9.10.1.4=h0fdc2d1_0
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_4
  - libgrpc=1.54.3=hb20ce57_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=3.21.12=hfc55251_2
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - markdown=3.8.2=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h89163eb_1
  - ml_dtypes=0.2.0=py310hcc13569_2
  - multidict=6.6.3=py310h89163eb_0
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h2d0b736_3
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openssl=3.5.2=h26f9b46_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyh8b19718_0
  - propcache=0.3.1=py310h89163eb_0
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.12=hd12c33a_0_cpython
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python_abi=3.10=8_cp310
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.1.10=hdb0a2a9_1
  - tensorflow=2.14.0=cuda118py310h148f8e3_0
  - tensorflow-base=2.14.0=cuda118py310h2e5981e_0
  - tensorflow-gpu=2.14.0=cuda118py310h0240f8b_0
  - termcolor=3.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yarl=1.20.1=py310h89163eb_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.24.0=py310h1d967bf_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cloudpickle==3.1.1
      - grpcio==1.74.0
      - imbalanced-learn==0.11.0
      - ipykernel==6.25.0
      - joblib==1.3.1
      - jupyter==1.0.0
      - keras==2.15.0
      - libclang==18.1.1
      - lightgbm==4.0.0
      - llvmlite==0.44.0
      - matplotlib==3.7.2
      - numba==0.61.2
      - numpy==1.24.3
      - pandas==2.0.3
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - plotly==5.15.0
      - protobuf==4.25.8
      - ptyprocess==0.7.0
      - pygments==2.19.2
      - pyparsing==3.0.9
      - pytz==2025.2
      - pyyaml==6.0.2
      - qtconsole==5.6.1
      - qtpy==2.4.3
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - seaborn==0.12.2
      - shap==0.48.0
      - slicer==0.0.8
      - statsmodels==0.14.0
      - tenacity==9.1.2
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.15.0
      - threadpoolctl==3.6.0
      - tornado==6.5.2
      - tqdm==4.65.0
      - wrapt==1.14.2
      - xgboost==1.7.6
prefix: /home/monkey/miniconda/envs/ml-tf
